#!/bin/bash
find toolkit. -type f -name "*.js*" -print0 | xargs -0 sed -i 's/if(/if (/'
find toolkit. -type f -name "*.js*" -print0 | xargs -0 sed -i 's/while(/while (/'
find toolkit. -type f -name "*.js*" -print0 | xargs -0 sed -i 's/for(/for (/'
find toolkit. -type f -name "*.js*" -print0 | xargs -0 sed -i 's/function(/function (/'
find toolkit. -type f -name "*.js*" -print0 | xargs -0 sed -i 's/switch(/switch (/'
find toolkit. -type f -name "*.js*" -print0 | xargs -0 sed -i 's/){/) {/'
find toolkit. -type f -name "*.js*" -exec java -jar ../trunk/jacop/tools/jscompiler.jar --js "{}" > /dev/null \;

